### ISSUE TITLE
Averaging Replicates

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [guanjue/IDEAS_2018#13]
Hello @guanjue, 

Hope you're well! 

I wanted to clarify the instructions for the `prepMat` regarding replicates as stated here: 
[https://github.com/guanjue/IDEAS_2018/blob/5881efae8e42ce711766d021a88e2cfe309a1f52/IDEAS_APP/readme_prepMat#L32](https://github.com/guanjue/IDEAS_2018/blob/5881efae8e42ce711766d021a88e2cfe309a1f52/IDEAS_APP/readme_prepMat#L32
)

How exactly do I average the files?

Can I assume the 1 millionth line in `ATAC_rep1.bed.gz` corresponds to the same region as the 1 millionth line in `ATAC_rep2.bed.gz`? 
The above assumes I've used the `prepMat` program to create the files.

If the answer is "yes" to my above question, I guess I could just iterate through each line in the `.bed.gz` files for a group of replicates and take the average. 
(i.e. take line 1 from 3 different replicate `.bed.gz` files and average these 3 numbers all from line 1 of the original file)

**Comment by YogiOnBioinformatics** [comment]
@guanjue 

Apologies, don't mean to bother.
Just wanted to follow up on this.

**Comment by guanjue** [comment]
Hi,

Sorry, for the late reply.

For Q1, the answer is yes. For each row, it will be a 200bp bins' read
counts for each replicate of each epigenomic feature.
So, yes, you can simply take the row-means as the average.

Best wishes.
Guanjue

**Comment by YogiOnBioinformatics** [comment]
Awesome, thanks so much!
