### ISSUE TITLE
Problematic Output?

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [guanjue/IDEAS_2018#15]
Hello @guanjue, 

I'm curious if this seems concerning to you.

My dataset was 7 cell types and 5 marks. 
However, the number of states in my heatmap seems to be 6. 

1. How exactly is that possible?
2. My heatmap looks suspicious since it's hard to distinguish between marks. What do you think?

I've attached the heatmap here.
[states.pdf](https://github.com/guanjue/IDEAS_2018/files/8227748/states.pdf)

My input and parameter files are also included below. 

[ES_stage.parafile.txt](https://github.com/guanjue/IDEAS_2018/files/8227754/ES_stage.parafile.txt)

[ES_stage.input.txt](https://github.com/guanjue/IDEAS_2018/files/8227755/ES_stage.input.txt)

**Comment by guanjue** [comment]
There do have some errors.

(1) Did you remove the black list regions?

(2) It looks like your cap signals are very high? What is the size of bins
in "all_regions.bed"?
We usually use 200bp bins. When the bin size is too large,  all epigenetic
features can mix together.

Best wishes.
Guanjue

**Comment by YogiOnBioinformatics** [comment]
(1) Yes, I removed the blacklist regions. 
(2) The max size was 200bp but there were quite a few regions that were smaller (i.e. a peak in some mark that was less than 200bp long). I made sure to follow your advice on that. 

Maybe the reason the numbers are high is since I used `prepMat` with the -norm flag. 
According to `./IDEAS_APP/readme_prepMat`, the -norm flag uses the following formula: "reads / total_reads * 20million"

Maybe, that's why it's so high. 

Would you suggest I run prepMat without norm and then do some type of my own normalization?
If so, any suggestions on the normalization method?

**Comment by guanjue** [comment]
Yes,  it is better to normalize outside prepMat.

If your normalized signal's signal-to-noise ratio is similar, it may also
be better to convert each sample's normalized read count to -log10-pvalue
based on a cross-sample global background Negative binomial model.
After that, you will have a reasonable value to cap the signal (e.g.
-log10(p-value) <= 16).

After that if you still see all features together, then it may be a file
label error in some steps. (one simple way to check that is to calculate
the global correlation between all samples. In a  correlation matrix with
mislabel, you may see some samples with active and negative features mixed
together.)

Best wishes.
Guanjue

**Comment by YogiOnBioinformatics** [comment]
Alright, I will go ahead and run `prepMat` without normalization. 

However, why does high numbers affect the output from a mathematical sense?
If all the counts are in terms of ((reads/total reads)*20 million), they're all in the same units. 

As well, after I get the raw counts from `prepMat`, would it make sense to run a standard normalization such as `TMM` from `EdgeR`?

**Comment by guanjue** [comment]
I am not sure there are mathematical explanations.
But for an example situation, suppose your sample has some
blacklist-like-regions (which are not removed) and they have extremely high
signals in all features.
Then, when you do normalization, it may compress all real signals into an
extremely small range.
In this case, if IDEAS have a lower limit for variance in practice (this
part I am not sure). Then, all real signals may be compressed into state
0,1,2.

Do you mind sharing some of your signal files, so I can check the signals?

For question2, the answer is no, if I remember correctly the standard edgeR
TMM is pairwise normalization which simultaneously changes the signals in
the both samples in each run.
You probably need to use a normalization method which can normalize against
one reference. (there may have new version of TMM that can do cross sample
normalization)

Best wishes.
Guanjue

**Comment by YogiOnBioinformatics** [comment]
I really appreciate being willing to look at some signal files. 
Here's a [link to the sample of files](https://drive.google.com/file/d/1LTTgAiA66JE5Gf_mPCBSzjRbn4c1rdAt/view?usp=sharing) (different cell lines and marks).

These files were created after running `prepMat` with `-norm` flag and then averaging the values across all replicates. 
Hence, each cell type and mark has 1 signal file, as per your suggestion.

Given that `-norm` multiplies by 20 million, the high numbers are no surprise. 


Regarding the second point, what about the `median of ratios` method used by `DESeq2`?
It creates a pseudo-reference and the details can be found [here](https://hbctraining.github.io/DGE_workshop/lessons/02_DGE_count_normalization.html#:~:text=DESeq2%2Dnormalized%20counts%3A%20Median%20of%20ratios%20method).
 
I greatly appreciate all your help! 
Please let me know what you find.

**Comment by guanjue** [comment]
I have plot a K4me3 vs K27me3 signal and they are highly correlated. It means either the signal label has some issue or the prepMat function has some issues. 

Do you mind to use the bigWigAverageOverBed in ucsc utilities to generate the reads count file for each 200bp bins?
If the K4me3 and K27me3 is no longer correlated, then it is the preMat function's issue.
If the K4me3 and K27me3 still highly correlated, then it may be some label error in the bigwig file or the bam file.

Best wishes.
Guanjue

**Comment by YogiOnBioinformatics** [comment]
I'll have to look deeper into the correlation.
I may end up using `bigWigAverageOverBed` if I still have issues with `prepMat`. 

Thanks as always! 

Have you had a chance to look at the [other issue](https://github.com/guanjue/IDEAS_2018/issues/14)?

**Comment by YogiOnBioinformatics** [comment]
I ended up running things again by taking the median between all replicates. 

Here are the [results](https://github.com/guanjue/IDEAS_2018/files/8365296/ES_stage.para0.pdf).

Do you have any comments on this result?

NOTE: I used the "TRUE" option for the color scaling.

**Comment by guanjue** [comment]
This result looks ok to me. Based on the heatmap, the K27me3 is not correlated with K4me3 this time. 

The signal looks a bit noisy. Depends on you downstream analysis it may not be a big issue. 

Btw, how is the epigenetic state track looks like? If it is too noisy for the downstream analysis, you may want to try S3V2-IDEAS pipeline. (Although the hypothesis of S3V2 normalization in S3V2-IDEAS pipeline may not fit with your dataset, it may still give you a better de-noised states track.)

**Comment by YogiOnBioinformatics** [comment]
Thanks for all your help! 😊

The downstream analysis for us is looking at the states for differential analysis. 
The S3V2 IDEAS may be worth it so thanks for the suggestion! 

I did not look at the Epigenetic State Tracks. 

The names of the tracks follow this nomenclature. 
`{insert id}.{insert number}.bb`
Example: `embryonic_stage.1.bb`

How do I know which cell line `1` corresponds to?

**Comment by guanjue** [comment]
NP. There should be one file named tracks.txt. It has the more detailed information for each *.bb file.

**Comment by YogiOnBioinformatics** [comment]
Perfect!

I found it and that explains it. 
Thanks so much! 😊

Closing this issue.
