### ISSUE TITLE
Run on 'build' mode

### ISSUE THREAD

**Issue by HouyuZhang** [guanjue/IDEAS_2018#6]
Hi! guanjue
I'm testing IDEAS recent days, followed by your example I have got the same result as it shown in your test_data/run_IDEAS_result where you offered a bed file named mm10_noblacklist_200bin.bed in where specifed chr1 and part of chr2 for analysis.
But, when I want to analyze the whole genome of mm10 , I use the following parameters according to my understanding of manual and it given the debug message, So, I'm confused that whether I misunderstood the parameter? 
This is my parameter file:
![image](https://user-images.githubusercontent.com/16659952/46577980-6d3b3e80-ca25-11e8-995b-9d636e54a7a0.png)
This is the result:
![image](https://user-images.githubusercontent.com/16659952/46577983-8348ff00-ca25-11e8-9097-7a1e3bb45281.png)
It seems that mm10.bed is absent under data/, but the annotation suggested I need data/mm10.genome, So , I'm sorry for bother you for debugging and many thanks!

**Comment by HouyuZhang** [comment]
In addition, I have processed the bam file seperately using the following command.
![image](https://user-images.githubusercontent.com/16659952/46578011-59440c80-ca26-11e8-9fc5-76b16e36408d.png)
And the bams are processed into *.bed.gz which looks like this:
![image](https://user-images.githubusercontent.com/16659952/46578026-afb14b00-ca26-11e8-81a7-c7e76811c0f0.png)
Whether this procedure matters in the failure. Thanks!

**Comment by guanjue** [comment]
Hi, Houyu

In this version, we do not use the build version. Instead, we provide the coordinates file 'mm10.200bin.txt'

You can use bedtools to generate the bins "mm10.200bin.sort.txt"
>>>
bedtools makewindows -g mm9.nochrM.genome -w 200 -i winnum > mm10.200bin.bed
cat mm10.bed | awk -F '\t' -v OFS=' ' '{print $1,$2,$3,"R"$4}' > mm10.200bin.txt
sort -k4,4 mm10.200bin.txt > mm10.200bin.sort.txt
>>>

Then, you need to get the read counts of each 200-bp bin along the genome and use that file as the *.*.input files.
(1) For these steps, you can first use deeptools (https://deeptools.readthedocs.io/en/develop/content/installation.html) to covert bamfile to bigwig file.
>>>
bamCoverage -b celltype.mark.bam -o celltype.mark.bw
>>>

(2) Then, use the bigWigAverageOverBed from uscs (http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigAverageOverBed) to convert the bigwig file to you signal tracks. For this "bigWigAverageOverBed", you need to sort your output by the bin IDs. You also need to cut the signal column as your input for IDEAS.
>>>
bigWigAverageOverBed celltype.mark.bw mm10.200bin.txt celltype.mark.tab
sort -k1,1 celltype.mark.tab | cut -f5 > celltype.mark.IDEAS_input_signal.txt
>>>

If you are using the read counts, you should also change the signal cap in the "run_IDEAS.parafile" file. 
"cap= 16"

Best wishes.
Guanjue

**Comment by yuzhang123** [comment]
Hi Guanjue, maybe we should include these in github as instructions for user to generate input data for IDEAS?


Thanks 

Yu
----- Original Message -----

**Comment by guanjue** [comment]
Sure, I can add these.

Best wishes.
Guanjue

**Comment by HouyuZhang** [comment]
Thanks for your reply,
I have used the R script /bin/makewindows,R to generate 200bp windows along the whole genome and  fed into IDEAS to get my primary result.
So, I don't understand why we should convert bam to bw and calculate the bigWigAverageOverBed? I used *.bam files to generate *.bed.gz file and it seems work well. (although I will try your method and compare the result :) )
Also, I want to bother you to ask how you add the annaotation besides the heatmap like this? Is there some guideline for annotation or you decide on your present epigenetic marks combinaton?
![image](https://user-images.githubusercontent.com/16659952/46579862-185eee80-ca4c-11e8-99f7-83740fb3073b.png)

Thanks you again!

**Comment by guanjue** [comment]
I haven't use the prepMat before, if it works, it will be fine. For using the *bw. file, if you want to normalize the library size, you can set the "norm= 1   #1: standardize by mean and std, 0: no normalization"  to scale each mark. 

For the input signal, you can also convert the read counts to -log(p-value) based on a negative binomial background model and then normalize the -log10(p-value) by our new normalization method called S3norm (https://github.com/guanjue/S3norm). In that case, the signal-to-noise ratio can be adjusted, which we think the results can better reflect the biological changes across multiple cell types.

For the annotation, we manually decide the annotation for each state.

**Comment by HouyuZhang** [comment]
Thank you guanjue for your kindly suggestions,
I will test all the methods you mentioned above and do comparison.
Best regards!
