### ISSUE TITLE
Imputation files

### ISSUE THREAD

**Issue by Lila14** [guanjue/IDEAS_2018#8]
Where are the output files for imputed chromatin marks?

**Comment by Lila14** [comment]
How will the files be named?

**Comment by yuzhang123** [comment]
It should have the mark name and cell name in the file name. If you can’t find it, probably I didn’t implement in the runme script.


----- Original Message -----

**Comment by Lila14** [comment]
I've attached the files I used to run IDEAs (with the test data). The other files were defaults. I removed MEP h3k27ac from the input file so that it would impute. 
[run_IDEAS.parafile.txt](https://github.com/guanjue/IDEAS_2018/files/2498288/run_IDEAS.parafile.txt)
[run_IDEAS.input.txt](https://github.com/guanjue/IDEAS_2018/files/2498289/run_IDEAS.input.txt)

**Comment by yuzhang123** [comment]
Maybe it is a bug? what if you switch row 2 and row 3 in input.txt?

The output file name should include ".impute.h3k27ac." in either where 
you run the code or your specified output folder.

**Comment by Lila14** [comment]
This didn't work. Would you mind attaching an example of a working imputation?

**Comment by guanjue** [comment]
I have generated the results with imputation.
The IDEAS can impute and save the missing data.
The results are saved in the .gz files
-rw-rw---- 1 gzx103 gzx103_collab 131K Oct 21 13:36 test_IDEAS.chr1.impute.ERY_ad.gz
-rw-rw---- 1 gzx103 gzx103_collab 160K Oct 21 13:36 test_IDEAS.chr1.impute.MEP.gz
-rw-rw---- 1 gzx103 gzx103_collab 181K Oct 21 13:36 test_IDEAS.chr1.impute.GMP.gz
-rw-rw---- 1 gzx103 gzx103_collab 323K Oct 21 13:36 test_IDEAS.chr1.impute2.ERY_ad.gz
-rw-rw---- 1 gzx103 gzx103_collab 595K Oct 21 13:36 test_IDEAS.chr1.impute2.MEP.gz
-rw-rw---- 1 gzx103 gzx103_collab 321K Oct 21 13:36 test_IDEAS.chr1.impute2.GMP.gz

If some of your cell types have missing marks (after you removing the MEP h3k27ac from the input file), the IDEAS will impute the marks.

However, if all of your cell types have all marks, the IDEAS will not impute the marks.

**Comment by Lila14** [comment]
Can you attach your input files?

**Comment by guanjue** [comment]
[run_IDEAS_with_imputation.input.txt](https://github.com/guanjue/IDEAS_2018/files/2499456/run_IDEAS_with_imputation.input.txt)

**Comment by guanjue** [comment]
[GMP.h3k4me3.1M.txt](https://github.com/guanjue/IDEAS_2018/files/2499457/GMP.h3k4me3.1M.txt)
[GMP.h3k27ac.1M.txt](https://github.com/guanjue/IDEAS_2018/files/2499458/GMP.h3k27ac.1M.txt)

These are the new input files

**Comment by Lila14** [comment]
It's still not producing imputation files for me. Can you send a zip file of everything you ran? Also, I keep having to change the file paths because you're using paths specific to your system. It's unlikely that this is the issue, but it might be easier if you used relative paths.

**Comment by guanjue** [comment]
Here is the zip file of the folder I run it. I deleted the output state files because the uploading limitation of the file size.
https://github.com/guanjue/IDEAS_2018/blob/master/test_data.zip

For the input file, it has to be the absolute paths. Otherwise, there output will not be generated.

**Comment by Lila14** [comment]
I got it working now. I think the issue was that I had to set "impute= All", instead of "impute= h3k27ac" for example.
